import prisma from "@/lib/prisma";
import { lookup } from "dns/promises";

function isPrivateAddress(address: string) {
  const n = address.toLowerCase(); if (n === "::1" || n === "::" || n.startsWith("fe80:") || n.startsWith("fc") || n.startsWith("fd")) return true;
  const o = n.split(".").map(Number); if (o.length !== 4 || o.some(Number.isNaN)) return false; const [a, b] = o;
  return a === 10 || a === 127 || a === 0 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168);
}
export async function getSafeEvolutionApiUrl(apiUrl: string) {
  let url: URL; try { url = new URL(apiUrl); } catch { throw new Error("Informe uma URL válida para a Evolution API."); }
  if (url.username || url.password || url.protocol !== "https:") throw new Error("A Evolution API deve usar uma URL HTTPS sem credenciais embutidas.");
  const addresses = await lookup(url.hostname, { all: true, verbatim: true }); if (!addresses.length || addresses.some((entry) => isPrivateAddress(entry.address))) throw new Error("A URL da Evolution API não pode apontar para endereços internos.");
  return url.toString().replace(/\/$/, "");
}
export interface WhatsappConnectionParams { provider: string; apiUrl?: string | null; token?: string | null; number?: string | null; }
export interface SendWhatsappParams { tenantId: string; recipient: string; type: "CONFIRMATION" | "REMINDER" | "INACTIVE" | "TEST" | "CANCEL_NOTIFICATION"; data: { clientName: string; serviceName: string; employeeName: string; dateStr: string; timeStr: string; inactiveDays?: number }; overrideMessage?: string; sensitive?: boolean; }
export function replaceMessagePlaceholders(t: string, d: SendWhatsappParams["data"]) { return t.replace(/\{nome\}/gi, d.clientName).replace(/\{servi[cç]o\}/gi, d.serviceName).replace(/\{profissional\}/gi, d.employeeName).replace(/\{data\}/gi, d.dateStr).replace(/\{hora\}/gi, d.timeStr).replace(/\{dias\}/gi, d.inactiveDays?.toString() || "30"); }
export function cleanPhoneNumber(phone: string) { const c = phone.replace(/\D/g, ""); return c.length === 10 || c.length === 11 ? `55${c}` : c; }
const paramsForMeta = (d: SendWhatsappParams["data"]) => [d.clientName, d.serviceName, d.employeeName, d.dateStr, d.timeStr];
function templateFor(t: { whatsappConfirmTemplate: string | null; whatsappReminderTemplate: string | null; whatsappInactiveTemplate: string | null; whatsappCancelNotifyTemplate: string | null }, type: SendWhatsappParams["type"]) { return type === "CONFIRMATION" ? t.whatsappConfirmTemplate || "" : type === "REMINDER" ? t.whatsappReminderTemplate || "" : type === "INACTIVE" ? t.whatsappInactiveTemplate || "" : type === "CANCEL_NOTIFICATION" ? t.whatsappCancelNotifyTemplate || "" : ""; }
function enabled(t: { whatsappConfirmEnabled: boolean; whatsappReminderEnabled: boolean; whatsappInactiveEnabled: boolean; whatsappCancelNotifyEnabled: boolean }, type: SendWhatsappParams["type"]) { return type === "TEST" || (type === "CONFIRMATION" && t.whatsappConfirmEnabled) || (type === "REMINDER" && t.whatsappReminderEnabled) || (type === "INACTIVE" && t.whatsappInactiveEnabled) || (type === "CANCEL_NOTIFICATION" && t.whatsappCancelNotifyEnabled); }
const errorText = (e: unknown) => e instanceof Error ? e.message.slice(0, 500) : "Erro desconhecido";
export async function verifyWhatsappConnection(p: WhatsappConnectionParams): Promise<{ success: boolean; status: string; error?: string }> {
  if (p.provider === "simulador") return { success: true, status: "SIMULATOR" }; if (!p.token || !p.number) return { success: false, status: "DISCONNECTED", error: "Token e identificador do número são obrigatórios." };
  try { if (p.provider === "evolution") { if (!p.apiUrl) return { success: false, status: "DISCONNECTED", error: "Informe a URL da Evolution API." }; const r = await fetch(`${await getSafeEvolutionApiUrl(p.apiUrl)}/instance/connectionState/${p.number}`, { headers: { apikey: p.token }, signal: AbortSignal.timeout(6000) }); const j = await r.json().catch(() => ({})); const state = j?.instance?.state || j?.state; return r.ok && state === "open" ? { success: true, status: "CONNECTED" } : { success: false, status: "DISCONNECTED", error: `Estado: ${state || `HTTP ${r.status}`}` }; } if (p.provider === "meta") { const r = await fetch(`https://graph.facebook.com/v19.0/${p.number}`, { headers: { Authorization: `Bearer ${p.token}` }, signal: AbortSignal.timeout(6000) }); const j = await r.json().catch(() => ({})); return r.ok ? { success: true, status: "CONNECTED" } : { success: false, status: "DISCONNECTED", error: j?.error?.message || `HTTP ${r.status}` }; } return { success: false, status: "DISCONNECTED", error: "Provedor desconhecido." }; } catch (e) { return { success: false, status: "DISCONNECTED", error: errorText(e) }; }
}
export async function sendWhatsappMessage(p: SendWhatsappParams): Promise<{ success: boolean; status: string; logId?: string; providerMessageId?: string; error?: string }> {
  const recipient = cleanPhoneNumber(p.recipient); let logMessage = p.sensitive ? "[Código de verificação enviado]" : "";
  try { const t = await prisma.tenant.findUnique({ where: { id: p.tenantId } }); if (!t) return { success: false, status: "FAILED", error: "Estabelecimento não encontrado." }; if (!t.whatsappEnabled) return { success: false, status: "FAILED", error: "Canal WhatsApp não está disponível para este estabelecimento." }; if (!enabled(t, p.type)) return { success: false, status: "FAILED", error: `Automação ${p.type} desativada.` }; const template = p.type === "TEST" ? p.overrideMessage || "Mensagem de teste do sistema." : templateFor(t, p.type); if (!template) return { success: false, status: "FAILED", error: "Template da automação não configurado." }; const text = replaceMessagePlaceholders(template, p.data); logMessage ||= t.whatsappProvider === "meta" && p.type !== "TEST" ? `[Template Meta: ${template}]` : text; let id: string | undefined; let status = "SENT";
    if (t.whatsappProvider === "simulador") status = "SIMULATED";
    else if (t.whatsappProvider === "evolution") { if (!t.whatsappApiUrl || !t.whatsappToken || !t.whatsappNumber) throw new Error("Parâmetros da Evolution API estão incompletos."); const r = await fetch(`${await getSafeEvolutionApiUrl(t.whatsappApiUrl)}/message/sendText/${t.whatsappNumber}`, { method: "POST", headers: { apikey: t.whatsappToken, "Content-Type": "application/json" }, body: JSON.stringify({ number: recipient, text }), signal: AbortSignal.timeout(10000) }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(`Evolution API retornou HTTP ${r.status}`); id = j?.key?.id || j?.message?.key?.id || j?.id; }
    else if (t.whatsappProvider === "meta") { if (!t.whatsappToken || !t.whatsappNumber) throw new Error("Token e Phone Number ID da Meta são obrigatórios."); const body = p.type === "TEST" ? { messaging_product: "whatsapp", to: recipient, type: "text", text: { body: text } } : { messaging_product: "whatsapp", to: recipient, type: "template", template: { name: template.trim(), language: { code: "pt_BR" }, components: [{ type: "body", parameters: paramsForMeta(p.data).map((text) => ({ type: "text", text })) }] } }; const r = await fetch(`https://graph.facebook.com/v19.0/${t.whatsappNumber}/messages`, { method: "POST", headers: { Authorization: `Bearer ${t.whatsappToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(10000) }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j?.error?.message || `Meta retornou HTTP ${r.status}`); id = j?.messages?.[0]?.id; } else throw new Error("Provedor de WhatsApp não suportado.");
    const log = await prisma.whatsappLog.create({ data: { tenantId: p.tenantId, recipient, message: logMessage, type: p.type, status, providerMessageId: id } }); return { success: true, status, logId: log.id, providerMessageId: id };
  } catch (e) { const msg = errorText(e); try { await prisma.whatsappLog.create({ data: { tenantId: p.tenantId, recipient, message: p.sensitive ? "Falha ao enviar código de verificação" : `Falha no envio: ${msg}`, type: p.type, status: "FAILED", failedAt: new Date() } }); } catch {} return { success: false, status: "FAILED", error: msg }; }
}
